theme = "zed_onedark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"
# 即使 Helix 版本较旧，新语法通常也会向下兼容
inline-diagnostics.cursor-line = "warning"
# inline-diagnostics.other-lines = "warning"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true
